version: '3.3'
services:
 nodeui:
    build: ./nodeapp/
    ports:
        - "80:3000"
    environment:
        API_SERVER_URL: "http://boot:8080/"
        API_SERVER_PORT:
        API_SERVER_TOKEN:
    links:
        - boot
    depends_on:
        - boot
 boot:
    build: ./testmysql/
    ports:
        - "8080:8080"
    links:
        - mysql
    depends_on:
        - mysql
 mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: rathod
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always